### ISSUE TITLE
Consider Vuepress

### ISSUE THREAD

**Issue by Emiller88** [selfhostedshow/wiki#26]
Over mkdocs or Hugo. https://vuepress.vuejs.org/

Still just uses markdown. If there's interested I'll throw together a quick PR.

**Comment by RealOrangeOne** [comment]
The current intention is to keep going with `mkdocs` for the next few months, and focus on getting the content in place. After that time we'll know exactly what we do and don't like from a framework, and what potential alternatives there are (the current frontrunner is Hugo), and be in a good place to make a decision, rather than now when everything's theoretical.

**Comment by Emiller88** [comment]
All good, I thought you all asked for recommendations in episode 13, my mistake.

**Comment by BCNelson** [comment]
@Emiller88 Vuepress is a good option we are looking into the bet option but will definitely not be changing to anything other than mkdocs until june at the earliest. If your interested in helping put together an example of the wiki in vuepress that would be great. Just don't expect us to do anything about it until June
